backend/api/urls.py
from django.urls import path, include
from api import views
from rest_framework import routers

app_name = 'api'
router = routers.SimpleRouter()
router.register('users', views.UserViewSet, basename='users')
router.register('amounts', views.AmoountsViewSet, basename='amounts')
router.register('c60', views.Common60ViewSet, basename='Common60')
router.register('c61', views.Common61ViewSet, basename='Common61')
router.register('c70', views.Common70ViewSet, basename='Common70')
router.register('cd', views.CommonDeadViewSet, basename='CommonDead')
router.register('jd', views.JudiciaryDeadViewSet, basename='JudiciaryDead')
router.register('dd', views.DoingDeadViewSet, basename='DoingDead')
router.register('pa', views.PublicAssistanceViewSet, basename='PublicAssistance')
router.register('msg', views.NotificationViewSet, basename='Notification')
router.register('lotteryc60', views.LotteryListView, basename='lotteryapi')
router.register('tabsgift', views.TableGiftViewSet, basename='tablegift')
router.register('tabgiftusr', views.TabGiftUsrViewSet, basename='tabgiftusr')
router.register('tabpay', views.TabPayViewSet, basename='tabpay')
router.register('tabwinner', views.TabWinnerViewSet, basename='tabwin')
router.register('socialmedia', views.SocialMediaViewSet, basename='socialmedia')
router.register('view', views.ViewPostViewSet, basename='view')
router.register('like', views.LikePostViewSet, basename='like')
router.register('comment', views.CommentPostViewSet, basename='comment')
router.register('newstext', views.NewsTextViewSet, basename='newstext')

urlpatterns = [
    path('', include(router.urls)),
    path('user/revoke/', views.RevokeToken.as_view(), name='revoketoken')
]

backend/base/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.utils.translation import gettext_lazy as _
from dj_rest_auth.views import PasswordResetConfirmView
from django.conf.urls.i18n import i18n_patterns
from decouple import config
from crm.views import assetlinks, privacyPolicy
# from rest_framework import permissions


urlpatterns = [
    path("api/", include('api.urls', namespace='api')),
    path('api/rest-auth/', include('dj_rest_auth.urls')),
    path('api/rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('api/rest-auth/password/reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path("i18n/", include("django.conf.urls.i18n")),
    path('.well-known/assetlinks.json', assetlinks),
    path('privacy-policy', privacyPolicy, name='privacyPolicy'),
]

urlpatterns += i18n_patterns(
    path('administrator/programmer/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('crm.urls', namespace='crm')),
)


if config('DEBUG', default=True, cast=bool) == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Hide Django rest framework Routers Api View Page Or config in settings.py
# if not DEBUG:
#     REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = (
#         "rest_framework.renderers.JSONRenderer",
#     )


admin.site.site_header = _('Control Panel')
admin.site.site_title = _('Control Panel')
admin.site.index_title = _('Wellcome to Control Panel')

# handler404 = 'crm.views.handler404'
# handler500 = 'crm.views.handler500'

backend/crm/urls.py
from django.urls import path
from crm import views
from django.contrib.auth.decorators import login_required

app_name = 'crm'
urlpatterns = [
    path('', views.home, name='home'),
    path('amounts/', login_required(views.AmountsList.as_view()), name='amount_list'),
    path('amounts/update/<int:pk>', login_required(views.AmountsUpdateView.as_view()), name='amount_update'),
    path('c60/', login_required(views.c60List.as_view()), name='c60_list'),
    path('subscribe/overview/<str:model>', views.overview, name='subscribe_overview'),
    path('c60/create/', login_required(views.C60CreateView.as_view()), name='c60_create'),
    path('c60/read/<int:pk>', login_required(views.C60ReadView.as_view()), name='c60_read'),
    path('c60/update/<int:pk>', login_required(views.C60UpdateView.as_view()), name='c60_update'),
    path('c60/delete/<int:pk>', login_required(views.C60DeleteView.as_view()), name='c60_delete'),
    path('c60/lottery/<str:title>', login_required(views.LotteryListView.as_view()), name='c60_lottery'),
    path('c60/lottery/add/<str:title>', views.AddtoLottery, name='c60_addtolottery'),
    path('c60/lottery/holding/<str:title>', views.HoldingLottery, name='c60_holdinglottery'),
    path('c60/lottery/draws/<str:title>', views.DrawsLottery, name='c60_draws'),
    path('c60/lottery/draws/detail/<str:name>', views.DrawsDetailLottery, name='c60_drawdetail'),
    path('c60/lottery/draws/delete/<str:name>', views.DrawsDeleteLottery, name='c60_drawdelete'),
    path('c61/', login_required(views.c61List.as_view()), name='c61_list'),
    path('c61/create/', login_required(views.C61CreateView.as_view()), name='c61_create'),
    path('c61/read/<int:pk>', login_required(views.C61ReadView.as_view()), name='c61_read'),
    path('c61/update/<int:pk>', login_required(views.C61UpdateView.as_view()), name='c61_update'),
    path('c61/delete/<int:pk>', login_required(views.C61DeleteView.as_view()), name='c61_delete'),
    path('c70/', login_required(views.c70List.as_view()), name='c70_list'),
    path('c70/create/', login_required(views.C70CreateView.as_view()), name='c70_create'),
    path('c70/read/<int:pk>', login_required(views.C70ReadView.as_view()), name='c70_read'),
    path('c70/update/<int:pk>', login_required(views.C70UpdateView.as_view()), name='c70_update'),
    path('c70/delete/<int:pk>', login_required(views.C70DeleteView.as_view()), name='c70_delete'),
    path('cd/', login_required(views.CdList.as_view()), name='cd_list'),
    path('cd/create/', login_required(views.CdCreateView.as_view()), name='cd_create'),
    path('cd/read/<int:pk>', login_required(views.CdReadView.as_view()), name='cd_read'),
    path('cd/update/<int:pk>', login_required(views.CdUpdateView.as_view()), name='cd_update'),
    path('cd/delete/<int:pk>', login_required(views.CdDeleteView.as_view()), name='cd_delete'),
    path('jd/', login_required(views.JdList.as_view()), name='jd_list'),
    path('jd/create/', login_required(views.JdCreateView.as_view()), name='jd_create'),
    path('jd/read/<int:pk>', login_required(views.JdReadView.as_view()), name='jd_read'),
    path('jd/update/<int:pk>', login_required(views.JdUpdateView.as_view()), name='jd_update'),
    path('jd/delete/<int:pk>', login_required(views.JdDeleteView.as_view()), name='jd_delete'),
    path('dd/', login_required(views.DdList.as_view()), name='dd_list'),
    path('dd/create/', login_required(views.DdCreateView.as_view()), name='dd_create'),
    path('dd/read/<int:pk>', login_required(views.DdReadView.as_view()), name='dd_read'),
    path('dd/update/<int:pk>', login_required(views.DdUpdateView.as_view()), name='dd_update'),
    path('dd/delete/<int:pk>', login_required(views.DdDeleteView.as_view()), name='dd_delete'),
    path('pa/', login_required(views.PaList.as_view()), name='pa_list'),
    path('pa/create/', login_required(views.PaCreateView.as_view()), name='pa_create'),
    path('pa/read/<int:pk>', login_required(views.PaReadView.as_view()), name='pa_read'),
    path('pa/update/<int:pk>', login_required(views.PaUpdateView.as_view()), name='pa_update'),
    path('pa/delete/<int:pk>', login_required(views.PaDeleteView.as_view()), name='pa_delete'),
    path('active/subscripe', login_required(views.ActiveSubscripe.as_view()), name='active_subscripe'),
    path('notification/', login_required(views.MessagesListView.as_view()), name='msg_list'),
    path('notification/send/', login_required(views.MessagesCreateView.as_view()), name='msg_create'),
    path('notification/sendto/<int:pk>', login_required(views.MessagesUserCreateView.as_view()), name='msg_user'),
    path('notification/view/<int:pk>', login_required(views.MessagesDetailView.as_view()), name='msg_view'),
    path('notification/update/<int:pk>', login_required(views.MessagesUpdateView.as_view()), name='msg_update'),
    path('notification/delete/<int:pk>', login_required(views.MessagesDeleteView.as_view()), name='msg_delete'),
    path('tabalegift/<str:tabname>', login_required(views.TableGiftListView.as_view()), name='tabgift'),
    path('tabalegift/create/', login_required(views.TableGiftCreateView.as_view()), name='tabalegift_create'),
    path('tabalegift/read/<int:pk>', login_required(views.TableGiftDetailView.as_view()), name='tabalegift_read'),
    path('tabalegift/update/<int:pk>', login_required(views.TableGiftUpdateView.as_view()), name='tabalegift_update'),
    path('tabalegift/delete/<int:pk>', login_required(views.TableGiftDeleteView.as_view()), name='tabalegift_delete'),
    path('participants', login_required(views.ParticipantsListView.as_view()), name='participants'),
    path('participants/read/<int:pk>', login_required(views.ParticipantsDetailView.as_view()), name='participants_read'),
    path('participants/update/<int:pk>', login_required(views.ParticipantsUpdateView.as_view()), name='participantst_update'),
    path('participants/delete/<int:pk>', login_required(views.ParticipantsDeleteView.as_view()), name='participants_delete'),
    path('holdtablottery/<str:tabname>', views.HoldTabLottery, name='holdtablottery'),
    path('tabwinners', login_required(views.TableWinnwers.as_view()), name='tabwinners'),
    path('socialmedia/newsend/', login_required(views.PostCreateView.as_view()), name='post_create'),
    path('socialmedia/list/', login_required(views.PostList.as_view()), name='post_list'),
    path('socialmedia/update/<int:pk>', login_required(views.PostUpdateView.as_view()), name='post_update'),
    path('socialmedia/delete/<int:pk>', login_required(views.PostDeleteView.as_view()), name='post_delete'),
    path('newstext/list/', login_required(views.NewsTextList.as_view()), name='news_list'),
    path('newstext/create/', login_required(views.NewsTextCreateView.as_view()), name='news_create'),
    path('newstext/update/<int:pk>', login_required(views.NewsTextUpdateView.as_view()), name='news_update'),
    path('newstext/delete/<int:pk>', login_required(views.NewsTextDeleteView.as_view()), name='news_delete'),
    path('comment/list/', login_required(views.CommentList.as_view()), name='comment_list'),
    path('comment/update/<int:pk>', login_required(views.CommentUpdateView.as_view()), name='comment_update'),
    path('comment/delete/<int:pk>', login_required(views.CommentDeleteView.as_view()), name='comment_delete'),
]

backend/crm/templates/crm/cdjd_list.html
{% extends "base.html" %}
{% load basetags %}
{% load static %}
{% load i18n %}
{% block head %}
    <link rel="stylesheet" href="{% static 'crm/css/style_searchbar.css' %}">
{% endblock head %}
{% block title %}
    {% trans "Subscription Dead" %}
{% endblock title %}
{% block content %}
    <div class="row mb-1"
         style="border:1px dashed;
                border-radius:15px;
                padding: 8px;background:#d7dcd84f;">
        <div class="col-3"></div>
        <div class="col-3 d-flex justify-content-center">
            {# Search Box #}
            <form action="" method="get">
                <div class="search-box ml-2">
                    <input type="text" name="q" placeholder="Search..." />
                    <button type="submit">
                        <i class="ri-search-line"></i>
                    </button>
                </div>
            </form>
        </div>
        <div class="col-3 d-flex justify-content-center">
            {# Filter Box #}
            <div class="btn-group dropend">
                <button type="button"
                        class="btn btn-secondary dropdown-toggle"
                        data-bs-toggle="dropdown"
                        aria-expanded="false">{% trans "Filter By" %}</button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li>
                        <a class="dropdown-item" href="?f=All">{% trans "All" %}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="?f=True">{% trans "Paid" %}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="?f=False">{% trans "UnPaid" %}</a>
                    </li>
                </ul>
            </div>
        </div>
        {% comment %} </div> {% endcomment %}
        <div class="col-3"></div>
    </div>
    <div class="row"
         style="border:1px dashed;
                border-radius:15px;
                padding: 8px;background:#d7dcd84f;">
        <table id="objs-table" class="table">
            <thead>
                <tr>
                    <th class="text-center" scope="col">{% trans "ID" %}</th>
                    <th class="text-center" scope="col">{% trans "User Submit" %}</th>
                    <th class="text-center" scope="col">{% trans "Name" %}</th>
                    <th class="text-center" scope="col">{% trans "IdCode" %}</th>
                    <th class="text-center" scope="col">{% trans "Contery" %}</th>
                    <th class="text-center" scope="col">{% trans "Phone" %}</th>
                    <th class="text-center" scope="col">{% trans "status" %}</th>
                    <th class="text-center" scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for obj in objects %}
                    <tr>
                        {% comment %} <th class="text-center" scope="row">{{ forloop.counter }}</th> {% endcomment %}
                        <td class="text-center">{{ obj.id }}</td>
                        <td class="text-center">{{ obj.usersubmit }}</td>
                        <td class="text-center">{{ obj.name }}</td>
                        <td class="text-center">{{ obj.idcode }}</td>
                        <td class="text-center">{{ obj.contery }}</td>
                        <td class="text-center">{{ obj.phone }}</td>
                        <td class="text-center">{{ obj.status }}</td>
                        <td class="text-center">
                            <!-- Read buttons -->
                            {% to_class_name obj as objctname %}
                            <a type="button"
                               class="btn btn-sm btn-success"
                               href="{% if objctname == "CommonDead" %} {% url 'crm:cd_read' obj.id %} {% else %} {% url 'crm:jd_read' obj.id %} {% endif %}">
                                <span class="ri-eye-line"></span>
                            </a>
                            <!-- Update buttons -->
                            <a type="button"
                               class="btn btn-sm btn-primary"
                               href="{% if objctname == "Common60" %} {% url 'crm:cd_update' obj.id %} {% else %} {% url 'crm:jd_update' obj.id %}  {% endif %}">
                                <span class="ri-edit-2-line"></span>
                            </a>
                            <!-- Delete buttons -->
                            <a type="button"
                               class="btn btn-sm btn-danger"
                               href="{% if objctname == "CommonDead" %} {% url 'crm:cd_delete' obj.id %} {% else %} {% url 'crm:jd_delete' obj.id %} {% endif %}">
                                <span class="ri-delete-bin-line"></span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {# ---- Paginator ---- #}
    {% if page_obj.has_other_pages %}
        <nav aria-label="Page navigation bootstrap">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">{% trans "First page" %}</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">&laquo;</span></a>
                    </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active" aria-current="page">
                            <span class="page-link">{{ num }}</span>
                        </li>
                    {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"><span aria-hidden="true">&raquo;</span></a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{% trans "Last page" %}</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
    {# ---- Paginator ---- #}
    {# ---- JavaScript ---- #}
    {% comment %} <script type="text/javascript">
     function OpenModal(id) {
         console.log("rrereer" + id);
         modal.insertAdjacentHTML("afterbegin", `{% include "crm/obj_read.html" %}`);
         modal.showModal();
     }
 </script> {% endcomment %}
    {# ---- JavaScript ---- #}
{% endblock content %}

backend/crm/templates/crm/comment_list.html
{% extends "base.html" %}
{% load basetags %}
{% load static %}
{% load i18n %}
{% block head %}
    <link rel="stylesheet" href="{% static 'crm/css/style_searchbar.css' %}">
{% endblock head %}
{% block title %}
    {% trans "Show List" %}
{% endblock title %}
{% block content %}
    <div class="row mb-1"
         style="border:1px dashed;
                border-radius:15px;
                padding: 8px;
                background:#d7dcd84f">
        <div class="col-3"></div>
        <div class="col-3 d-flex justify-content-center">
            {# Search Box #}
            <form action="" method="get">
                <div class="search-box ml-2">
                    <input type="text" name="q" placeholder="Search..." />
                    <button type="submit">
                        <i class="ri-search-line"></i>
                    </button>
                </div>
            </form>
        </div>
        <div class="col-3 d-flex justify-content-center">
            {# Filter Box #}
            <div class="btn-group dropend">
                <button type="button"
                        class="btn btn-secondary dropdown-toggle"
                        data-bs-toggle="dropdown"
                        aria-expanded="false">{% trans "Filter By" %}</button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li>
                        <a class="dropdown-item" href="?f=all">{% trans "All" %}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="?f=active">{% trans "Active" %}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="?f=unactive">{% trans "Unactive" %}</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    <div class="row"
         style="border:1px dashed;
                border-radius:15px;
                padding: 8px;
                background:#d7dcd84f">
        <table id="objs-table" class="table">
            <thead>
                <tr>
                    <th class="text-center" scope="col">{% trans "ID" %}</th>
                    <th class="text-center" scope="col">{% trans "User" %}</th>
                    <th class="text-center" scope="col">{% trans "Social Media" %}</th>
                    <th class="text-center" scope="col">{% trans "Text" %}</th>
                    <th class="text-center" scope="col">{% trans "Create Date" %}</th>
                    <th class="text-center" scope="col">{% trans "Active" %}</th>
                    <th class="text-center" scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for obj in objects %}
                    <tr>
                        {% comment %} <th class="text-center" scope="row">{{ forloop.counter }}</th> {% endcomment %}
                        <td class="text-center">{{ obj.id }}</td>
                        <td class="text-center">{{ obj.user }}</td>
                        <td class="text-center">{{ obj.socialmedia }}</td>
                        <td class="text-center">{{ obj.text }}</td>
                        <td class="text-center">{{ obj.createdt|date:"Y-m-d (H:i)" }}</td>
                        <td class="text-center">{{ obj.active }}</td>
                        <td class="text-center">
                            <!-- Read buttons -->
                            <!-- Update buttons -->
                            <a type="button"
                               class="btn btn-sm btn-primary"
                               href="{% url 'crm:comment_update' obj.id %}">
                                <span class="ri-edit-2-line"></span>
                            </a>
                            <!-- Delete buttons -->
                            <a type="button"
                               class="btn btn-sm btn-danger"
                               href="{% url 'crm:comment_delete' obj.id %}">
                                <span class="ri-delete-bin-line"></span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {# ---- Paginator ---- #}
    {% if page_obj.has_other_pages %}
        <nav aria-label="Page navigation bootstrap">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">First page</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">&laquo;</span></a>
                    </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active" aria-current="page">
                            <span class="page-link">{{ num }}</span>
                        </li>
                    {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"><span aria-hidden="true">&raquo;</span></a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last page</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
    {# ---- Paginator ---- #}
{% endblock content %}

backend/crm/templates/crm/dd_list.html
{% extends "base.html" %}
{% load basetags %}
{% load static %}
{% load i18n %}
{% block head %}
    <link rel="stylesheet" href="{% static 'crm/css/style_searchbar.css' %}">
{% endblock head %}
{% block title %}
    {% trans "Subscription Doing Dead" %}
{% endblock title %}
{% block content %}
    <div class="row mb-1"
         style="border:1px dashed;
                border-radius:15px;
                padding: 8px;
                background:#d7dcd84f">
        <div class="col-3"></div>
        <div class="col-3 d-flex justify-content-center">
            {# Search Box #}
            <form action="" method="get">
                <div class="search-box ml-2">
                    <input type="text" name="q" placeholder="Search..." />
                    <button type="submit">
                        <i class="ri-search-line"></i>
                    </button>
                </div>
            </form>
        </div>
        <div class="col-3 d-flex justify-content-center">
            {# Filter Box #}
            <div class="btn-group dropend">
                <button type="button"
                        class="btn btn-secondary dropdown-toggle"
                        data-bs-toggle="dropdown"
                        aria-expanded="false">{% trans "Filter By" %}</button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li>
                        <a class="dropdown-item" href="?f=All">{% trans "All" %}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="?f=True">{% trans "Paid" %}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="?f=False">{% trans "UnPaid" %}</a>
                    </li>
                </ul>
            </div>
        </div>
        {% comment %} </div> {% endcomment %}
        <div class="col-3"></div>
    </div>
    <div class="row"
         style="border:1px dashed;
                border-radius:15px;
                padding: 8px;
                background:#d7dcd84f">
        <table id="objs-table" class="table">
            <thead>
                <tr>
                    <th class="text-center" scope="col">{% trans "ID" %}</th>
                    <th class="text-center" scope="col">{% trans "User Submit" %}</th>
                    <th class="text-center" scope="col">{% trans "Name" %}</th>
                    <th class="text-center" scope="col">{% trans "Amount" %}</th>
                    <th class="text-center" scope="col">{% trans "Year Prayer" %}</th>
                    <th class="text-center" scope="col">{% trans "Year fasting" %}</th>
                    <th class="text-center" scope="col">{% trans "Pilgrimage" %}</th>
                    <th class="text-center" scope="col">{% trans "Phone" %}</th>
                    <th class="text-center" scope="col">{% trans "Contery" %}</th>
                    <th class="text-center" scope="col">{% trans "Status" %}</th>
                    <th class="text-center" scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for obj in objects %}
                    <tr>
                        {% comment %} <th class="text-center" scope="row">{{ forloop.counter }}</th> {% endcomment %}
                        <td class="text-center">{{ obj.id }}</td>
                        <td class="text-center">{{ obj.usersubmit }}</td>
                        <td class="text-center">{{ obj.name }}</td>
                        <td class="text-center">{{ obj.amount }}</td>
                        <td class="text-center">{{ obj.yearprayer }}</td>
                        <td class="text-center">{{ obj.yearfasting }}</td>
                        <td class="text-center">{{ obj.pilgrimage }}</td>
                        <td class="text-center">{{ obj.phone }}</td>
                        <td class="text-center">{{ obj.contery }}</td>
                        <td class="text-center">{{ obj.status }}</td>
                        <td class="text-center">
                            <!-- Read buttons -->
                            {% to_class_name obj as objctname %}
                            <a type="button"
                               class="btn btn-sm btn-success"
                               href="{% url 'crm:dd_read' obj.id %}">
                                <span class="ri-eye-line"></span>
                            </a>
                            <!-- Update buttons -->
                            <a type="button"
                               class="btn btn-sm btn-primary"
                               href="{% url 'crm:dd_update' obj.id %}">
                                <span class="ri-edit-2-line"></span>
                            </a>
                            <!-- Delete buttons -->
                            <a type="button"
                               class="btn btn-sm btn-danger"
                               href="{% url 'crm:dd_delete' obj.id %}">
                                <span class="ri-delete-bin-line"></span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {# ---- Paginator ---- #}
    {% if page_obj.has_other_pages %}
        <nav aria-label="Page navigation bootstrap">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">First page</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">&laquo;</span></a>
                    </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active" aria-current="page">
                            <span class="page-link">{{ num }}</span>
                        </li>
                    {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"><span aria-hidden="true">&raquo;</span></a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last page</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
    {# ---- Paginator ---- #}
    {# ---- JavaScript ---- #}
    {% comment %} <script type="text/javascript">
     function OpenModal(id) {
         console.log("rrereer" + id);
         modal.insertAdjacentHTML("afterbegin", `{% include "crm/obj_read.html" %}`);
         modal.showModal();
     }
 </script> {% endcomment %}
    {# ---- JavaScript ---- #}
{% endblock content %}