backend/accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth.decorators import login_required


app_name = 'accounts'
urlpatterns = [
    path('login/', views.userLogin, name='login'),
    path('register/', views.userRegister, name='register'),
    path('logout/', views.LogoutPage, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/change/password', views.profilepass, name='profilepass'),
    path('users/', login_required(views.UsersListView.as_view()), name='user_list'),
    path('users/overview', views.overview, name='users_overview'),
    path('users/create', login_required(views.UserCreateView.as_view()), name='user_create'),
    path('users/detail/<int:pk>', login_required(views.UserDetailView.as_view()), name='user_detail'),
    path('users/update/<int:pk>', login_required(views.UsersUpdateView.as_view()), name='user_update'),
    path('users/update/password/<int:pk>', login_required(views.UsersUpdatePassView.as_view()), name='user_updatepassword'),
    path('users/delete/<int:pk>', login_required(views.UsersDeleteView.as_view()), name='user_delete'),
]

backend/api/urls.py
from django.urls import path, include
from api import views
from rest_framework import routers

app_name = 'api'
router = routers.SimpleRouter()
router.register('users', views.UserViewSet, basename='users')
router.register('amounts', views.AmoountsViewSet, basename='amounts')
router.register('c60', views.Common60ViewSet, basename='Common60')
router.register('c61', views.Common61ViewSet, basename='Common61')
router.register('c70', views.Common70ViewSet, basename='Common70')
router.register('cd', views.CommonDeadViewSet, basename='CommonDead')
router.register('jd', views.JudiciaryDeadViewSet, basename='JudiciaryDead')
router.register('dd', views.DoingDeadViewSet, basename='DoingDead')
router.register('pa', views.PublicAssistanceViewSet, basename='PublicAssistance')
router.register('msg', views.NotificationViewSet, basename='Notification')
router.register('lotteryc60', views.LotteryListView, basename='lotteryapi')
router.register('tabsgift', views.TableGiftViewSet, basename='tablegift')
router.register('tabgiftusr', views.TabGiftUsrViewSet, basename='tabgiftusr')
router.register('tabpay', views.TabPayViewSet, basename='tabpay')
router.register('tabwinner', views.TabWinnerViewSet, basename='tabwin')
router.register('socialmedia', views.SocialMediaViewSet, basename='socialmedia')
router.register('view', views.ViewPostViewSet, basename='view')
router.register('like', views.LikePostViewSet, basename='like')
router.register('comment', views.CommentPostViewSet, basename='comment')
router.register('newstext', views.NewsTextViewSet, basename='newstext')

urlpatterns = [
    path('', include(router.urls)),
    path('user/revoke/', views.RevokeToken.as_view(), name='revoketoken')
]

backend/base/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.utils.translation import gettext_lazy as _
from dj_rest_auth.views import PasswordResetConfirmView
from django.conf.urls.i18n import i18n_patterns
from decouple import config
from crm.views import assetlinks, privacyPolicy
# from rest_framework import permissions


urlpatterns = [
    path("api/", include('api.urls', namespace='api')),
    path('api/rest-auth/', include('dj_rest_auth.urls')),
    path('api/rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('api/rest-auth/password/reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path("i18n/", include("django.conf.urls.i18n")),
    path('.well-known/assetlinks.json', assetlinks),
    path('privacy-policy', privacyPolicy, name='privacyPolicy'),
]

urlpatterns += i18n_patterns(
    path('administrator/programmer/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('crm.urls', namespace='crm')),
)


if config('DEBUG', default=True, cast=bool) == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Hide Django rest framework Routers Api View Page Or config in settings.py
# if not DEBUG:
#     REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = (
#         "rest_framework.renderers.JSONRenderer",
#     )


admin.site.site_header = _('Control Panel')
admin.site.site_title = _('Control Panel')
admin.site.index_title = _('Wellcome to Control Panel')

# handler404 = 'crm.views.handler404'
# handler500 = 'crm.views.handler500'

backend/crm/urls.py
from django.urls import path
from crm import views
from django.contrib.auth.decorators import login_required

app_name = 'crm'
urlpatterns = [
    path('', views.home, name='home'),
    path('amounts/', login_required(views.AmountsList.as_view()), name='amount_list'),
    path('amounts/update/<int:pk>', login_required(views.AmountsUpdateView.as_view()), name='amount_update'),
    path('c60/', login_required(views.c60List.as_view()), name='c60_list'),
    path('subscribe/overview/<str:model>', views.overview, name='subscribe_overview'),
    path('c60/create/', login_required(views.C60CreateView.as_view()), name='c60_create'),
    path('c60/read/<int:pk>', login_required(views.C60ReadView.as_view()), name='c60_read'),
    path('c60/update/<int:pk>', login_required(views.C60UpdateView.as_view()), name='c60_update'),
    path('c60/delete/<int:pk>', login_required(views.C60DeleteView.as_view()), name='c60_delete'),
    path('c60/lottery/<str:title>', login_required(views.LotteryListView.as_view()), name='c60_lottery'),
    path('c60/lottery/add/<str:title>', views.AddtoLottery, name='c60_addtolottery'),
    path('c60/lottery/holding/<str:title>', views.HoldingLottery, name='c60_holdinglottery'),
    path('c60/lottery/draws/<str:title>', views.DrawsLottery, name='c60_draws'),
    path('c60/lottery/draws/detail/<str:name>', views.DrawsDetailLottery, name='c60_drawdetail'),
    path('c60/lottery/draws/delete/<str:name>', views.DrawsDeleteLottery, name='c60_drawdelete'),
    path('c61/', login_required(views.c61List.as_view()), name='c61_list'),
    path('c61/create/', login_required(views.C61CreateView.as_view()), name='c61_create'),
    path('c61/read/<int:pk>', login_required(views.C61ReadView.as_view()), name='c61_read'),
    path('c61/update/<int:pk>', login_required(views.C61UpdateView.as_view()), name='c61_update'),
    path('c61/delete/<int:pk>', login_required(views.C61DeleteView.as_view()), name='c61_delete'),
    path('c70/', login_required(views.c70List.as_view()), name='c70_list'),
    path('c70/create/', login_required(views.C70CreateView.as_view()), name='c70_create'),
    path('c70/read/<int:pk>', login_required(views.C70ReadView.as_view()), name='c70_read'),
    path('c70/update/<int:pk>', login_required(views.C70UpdateView.as_view()), name='c70_update'),
    path('c70/delete/<int:pk>', login_required(views.C70DeleteView.as_view()), name='c70_delete'),
    path('cd/', login_required(views.CdList.as_view()), name='cd_list'),
    path('cd/create/', login_required(views.CdCreateView.as_view()), name='cd_create'),
    path('cd/read/<int:pk>', login_required(views.CdReadView.as_view()), name='cd_read'),
    path('cd/update/<int:pk>', login_required(views.CdUpdateView.as_view()), name='cd_update'),
    path('cd/delete/<int:pk>', login_required(views.CdDeleteView.as_view()), name='cd_delete'),
    path('jd/', login_required(views.JdList.as_view()), name='jd_list'),
    path('jd/create/', login_required(views.JdCreateView.as_view()), name='jd_create'),
    path('jd/read/<int:pk>', login_required(views.JdReadView.as_view()), name='jd_read'),
    path('jd/update/<int:pk>', login_required(views.JdUpdateView.as_view()), name='jd_update'),
    path('jd/delete/<int:pk>', login_required(views.JdDeleteView.as_view()), name='jd_delete'),
    path('dd/', login_required(views.DdList.as_view()), name='dd_list'),
    path('dd/create/', login_required(views.DdCreateView.as_view()), name='dd_create'),
    path('dd/read/<int:pk>', login_required(views.DdReadView.as_view()), name='dd_read'),
    path('dd/update/<int:pk>', login_required(views.DdUpdateView.as_view()), name='dd_update'),
    path('dd/delete/<int:pk>', login_required(views.DdDeleteView.as_view()), name='dd_delete'),
    path('pa/', login_required(views.PaList.as_view()), name='pa_list'),
    path('pa/create/', login_required(views.PaCreateView.as_view()), name='pa_create'),
    path('pa/read/<int:pk>', login_required(views.PaReadView.as_view()), name='pa_read'),
    path('pa/update/<int:pk>', login_required(views.PaUpdateView.as_view()), name='pa_update'),
    path('pa/delete/<int:pk>', login_required(views.PaDeleteView.as_view()), name='pa_delete'),
    path('active/subscripe', login_required(views.ActiveSubscripe.as_view()), name='active_subscripe'),
    path('notification/', login_required(views.MessagesListView.as_view()), name='msg_list'),
    path('notification/send/', login_required(views.MessagesCreateView.as_view()), name='msg_create'),
    path('notification/sendto/<int:pk>', login_required(views.MessagesUserCreateView.as_view()), name='msg_user'),
    path('notification/view/<int:pk>', login_required(views.MessagesDetailView.as_view()), name='msg_view'),
    path('notification/update/<int:pk>', login_required(views.MessagesUpdateView.as_view()), name='msg_update'),
    path('notification/delete/<int:pk>', login_required(views.MessagesDeleteView.as_view()), name='msg_delete'),
    path('tabalegift/<str:tabname>', login_required(views.TableGiftListView.as_view()), name='tabgift'),
    path('tabalegift/create/', login_required(views.TableGiftCreateView.as_view()), name='tabalegift_create'),
    path('tabalegift/read/<int:pk>', login_required(views.TableGiftDetailView.as_view()), name='tabalegift_read'),
    path('tabalegift/update/<int:pk>', login_required(views.TableGiftUpdateView.as_view()), name='tabalegift_update'),
    path('tabalegift/delete/<int:pk>', login_required(views.TableGiftDeleteView.as_view()), name='tabalegift_delete'),
    path('participants', login_required(views.ParticipantsListView.as_view()), name='participants'),
    path('participants/read/<int:pk>', login_required(views.ParticipantsDetailView.as_view()), name='participants_read'),
    path('participants/update/<int:pk>', login_required(views.ParticipantsUpdateView.as_view()), name='participantst_update'),
    path('participants/delete/<int:pk>', login_required(views.ParticipantsDeleteView.as_view()), name='participants_delete'),
    path('holdtablottery/<str:tabname>', views.HoldTabLottery, name='holdtablottery'),
    path('tabwinners', login_required(views.TableWinnwers.as_view()), name='tabwinners'),
    path('socialmedia/newsend/', login_required(views.PostCreateView.as_view()), name='post_create'),
    path('socialmedia/list/', login_required(views.PostList.as_view()), name='post_list'),
    path('socialmedia/update/<int:pk>', login_required(views.PostUpdateView.as_view()), name='post_update'),
    path('socialmedia/delete/<int:pk>', login_required(views.PostDeleteView.as_view()), name='post_delete'),
    path('newstext/list/', login_required(views.NewsTextList.as_view()), name='news_list'),
    path('newstext/create/', login_required(views.NewsTextCreateView.as_view()), name='news_create'),
    path('newstext/update/<int:pk>', login_required(views.NewsTextUpdateView.as_view()), name='news_update'),
    path('newstext/delete/<int:pk>', login_required(views.NewsTextDeleteView.as_view()), name='news_delete'),
    path('comment/list/', login_required(views.CommentList.as_view()), name='comment_list'),
    path('comment/update/<int:pk>', login_required(views.CommentUpdateView.as_view()), name='comment_update'),
    path('comment/delete/<int:pk>', login_required(views.CommentDeleteView.as_view()), name='comment_delete'),
]

backend/accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label=_('Password'), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_('Password confirmation'), widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ('username', 'phone', 'email', 'is_active', 'is_staff', 'is_superuser')

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.name != "is_active" and visible.name != "is_staff" and visible.name != "is_superuser":
                visible.field.widget.attrs['class'] = 'form-control'

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError('Passwords don\'t match')
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    # password = ReadOnlyPasswordHashField()

    class Meta:
        model = get_user_model()
        fields = ('username', 'phone', 'email', 'fcmtoken', 'is_active', 'is_staff', 'is_superuser')

        # add User Permission setting to custom form
        # fields = ('username', 'phone', 'email', 'fcmtoken', 'is_active', 'is_staff', 'is_superuser', 'user_permissions')

    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.name != "is_active" and visible.name != "is_staff" and visible.name != "is_superuser":
                visible.field.widget.attrs['class'] = 'form-control'

    def clean_password(self):
        return self.initial['password']


class ChangePasswordFrom(forms.ModelForm):
    # username = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    password1 = forms.CharField(label=_('Password'), widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(label=_('Password confirmation'),
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'placeholder': 'Re-Enter Password'}))

    class Meta:
        model = get_user_model()
        fields = ('password1', 'password2')

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError('Passwords don\'t match')
        else:
            return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'type': 'username', 'name': 'logusername', 'class': 'form-style', 'placeholder': 'Username', 'id': 'logusername', 'autocomplete': 'off'}),)
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'type': 'password', 'name': 'logpass', 'class': 'form-style', 'placeholder': 'Password', 'id': 'logpass', 'autocomplete': 'off'}),)


class LoginFormAR(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'type': 'username', 'name': 'logusername', 'class': 'form-style', 'placeholder': 'اسم المستخدم', 'id': 'logusername', 'autocomplete': 'off', 'lang': 'ar'}),)
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'type': 'password', 'name': 'logpass', 'class': 'form-style', 'placeholder': 'كلمة السر خاصتك', 'id': 'logpass', 'autocomplete': 'off', 'lang': 'ar'}),)

backend/accounts/templates/accounts/overview.html
{% extends "base.html" %}
{% load static %}
{% block head %}
{% endblock head %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8 d-flex justify-content-center">
                <h2>{{ headerTitle }}</h2>
            </div>
            <div class="col-2"></div>
        </div>
        {# Payment Chart #}
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="p-2 border d-flex justify-content-center"
                     style="background-color:#c1f6e375;
                            border-radius: 15px">
                    <div id="container" style="width: 75%;">
                        <canvas id="users_chart"></canvas>
                    </div>
                </div>
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="p-2 border"
                     style="background-color:#c1f6e375;
                            border-radius: 15px">
                    <div class="row">
                        <div class="col-8">Total:</div>
                        <div class="col-4">{{ totalcount }}</div>
                    </div>
                    <div class="row">
                        <div class="col-8">Active Users:</div>
                        <div class="col-4">{{ datausers.0 }}</div>
                    </div>
                    <div class="row">
                        <div class="col-8">Staff Users:</div>
                        <div class="col-4">{{ datausers.1 }}</div>
                    </div>
                       <div class="row">
                        <div class="col-8">Super Users:</div>
                        <div class="col-4">{{ datausers.2 }}</div>
                    </div>
                </div>
            </div>
            <div class="col-2"></div>
        </div>
        <br>
        {# Contery Chart #}
        {% comment %} <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="p-2 border d-flex justify-content-center"
                     style="background-color:#c1f6e375;
                            border-radius: 15px">
                    <div id="container" style="width: 75%;">
                        <canvas id="contery_chart"></canvas>
                    </div>
                </div>
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="p-2 border"
                     style="background-color:#c1f6e375;
                            border-radius: 15px">
                    <div class="row">
                        <div class="col-8">Total Contery:</div>
                        <div class="col-4">{{ totalcountery }}</div>
                    </div>
                </div>
            </div>
            <div class="col-2"></div>
        </div> {% endcomment %}

    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>
    var ctxusers = document.getElementById('users_chart').getContext('2d');
    var configusers = {
        type: 'pie',
        data: {
            datasets: [{
                data: {{ datausers|safe }},
                backgroundColor: [
                    '#00FF0C', '#B0BA87','#E6EB09'
                ],
                label: 'Users'
            }],
            labels: {{ labelsusers|safe }}
        },
        options: {
            responsive: true
        }
    };

    window.onload = function() {
        window.usersPie = new Chart(ctxusers, configusers);
    };
</script>
{% endblock content %}

backend/accounts/templates/accounts/users_detail.html
{% extends "base.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'crm/css/printstyle.css' %}">
{% endblock head %}
{% block content %}
    <div id="print_this">
        <table id="objs-table" class="table">
            <thead>
                <tr>
                    <th>ID:</th>
                    <th>{{ obj.id }}</th>
                </tr>
                <tr>
                    <th>Username:</th>
                    <th>{{ obj.username }}</th>
                </tr>
                <tr>
                    <th>Phone:</th>
                    <th>{{ obj.phone }}</th>
                </tr>
                <tr>
                    <th>Email:</th>
                    <th>{{ obj.email }}</th>
                </tr>
                <tr>
                    <th>Register Date:</th>
                    <th>{{ obj.regdate|date:"Y-m-d (H:i)" }}</th>
                </tr>
                <tr>
                    <th>Updated:</th>
                    <th>{{ obj.updated|date:"Y-m-d (H:i)" }}</th>
                </tr>
                <tr>
                    <th>Active:</th>
                    <th>{{ obj.is_active }}</th>
                </tr>
                <tr>
                    <th>Staff:</th>
                    <th>{{ obj.is_staff }}</th>
                </tr>
                <tr>
                    <th>Superuser:</th>
                    <th>{{ obj.is_superuser }}</th>
                </tr>
            </thead>
        </table>
    </div>
    <center>
        <div class="text-center" style="margin-top:20px;">
            <button class="print-button noPrint"  onclick="printdiv()" target="_blank">
                <span class="print-icon"></span>
            </button>
        </div>
    </center>
{% endblock content %}

backend/accounts/templates/accounts/users_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block head %}
    <link rel="stylesheet" href="{% static 'crm/css/style_searchbar.css' %}">
{% endblock head %}
{% load basetags %}
{% block content %}
    <div class="row mb-1"
         style="border:1px dashed;
                border-radius:15px;
                padding: 8px;
                background:#d7dcd84f">
        <div class="col-3"></div>
        <div class="col-3 d-flex justify-content-center">
            {# Search Box #}
            <form action="" method="get">
                <div class="search-box ml-2">
                    <input type="text" name="q" placeholder="Search..." />
                    <button type="submit">
                        <i class="ri-search-line"></i>
                    </button>
                </div>
            </form>
        </div>
        <div class="col-3 d-flex justify-content-center">
            {# Filter Box #}
            <div class="btn-group dropend">
                <button type="button"
                        class="btn btn-secondary dropdown-toggle"
                        data-bs-toggle="dropdown"
                        aria-expanded="false">{% trans "Filter By" %}</button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li>
                        <a class="dropdown-item" href="?f=All">{% trans "All" %}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="?f=True">{% trans "Active" %}</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="?f=False">{% trans "Deactivate" %}</a>
                    </li>
                </ul>
            </div>
        </div>
        {% comment %} </div> {% endcomment %}
        <div class="col-3"></div>
    </div>
    <div class="row"
         style="border:1px dashed;
                border-radius:15px;
                padding: 8px;
                background:#d7dcd84f">
        <table id="objs-table" class="table">
            <thead>
                <tr>
                    <th class="text-center" scope="col">ID</th>
                    <th class="text-center" scope="col">Username</th>
                    <th class="text-center" scope="col">Phone</th>
                    <th class="text-center" scope="col">Email</th>
                    <th class="text-center" scope="col">Register Date</th>
                    {% comment %} <th class="text-center" scope="col">updated</th> {% endcomment %}
                    <th class="text-center" scope="col">Active</th>
                    <th class="text-center" scope="col">Staff</th>
                    <th class="text-center" scope="col">Superuser</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in objects %}
                    <tr>
                        {% comment %} <th class="text-center" scope="row">{{ forloop.counter }}</th> {% endcomment %}
                        <td class="text-center">{{ obj.id }}</td>
                        <td class="text-center">{{ obj.username }}</td>
                        <td class="text-center">{{ obj.phone }}</td>
                        <td class="text-center">{{ obj.email }}</td>
                        <td class="text-center">{{ obj.regdate|date:"Y-m-d (H:i)" }}</td>
                        {% comment %} <td class="text-center">{{ obj.updated }}</td> {% endcomment %}
                        <td class="text-center">{{ obj.is_active }}</td>
                        <td class="text-center">{{ obj.is_staff }}</td>
                        <td class="text-center">{{ obj.is_superuser }}</td>
                        <td class="text-center">
                            <!-- SendMSG buttons -->
                            <a type="button"
                               class="btn btn-sm btn-secondary"
                               href="{% url 'crm:msg_user' obj.id %}">
                                <span class="ri-message-2-fill"></span>
                            </a>
                            <!-- Read buttons -->
                            {% to_class_name obj as objctname %}
                            <a type="button"
                               class="btn btn-sm btn-success"
                               href="{% url 'accounts:user_detail' obj.id %}">
                                <span class="ri-eye-line"></span>
                            </a>
                            <!-- Update buttons -->
                            <a type="button"
                               class="btn btn-sm btn-primary"
                               href="{% url 'accounts:user_update' obj.id %}">
                                <span class="ri-edit-2-line"></span>
                            </a>
                            <!-- Update Password buttons -->
                            <a type="button"
                               class="btn btn-sm btn-warning"
                               href="{% url 'accounts:user_updatepassword' obj.id %}">
                                <span class="ri-lock-unlock-line"></span>
                            </a>
                            <!-- Delete buttons -->
                            <a type="button"
                               class="btn btn-sm btn-danger"
                               href="{% url 'accounts:user_delete' obj.id %}">
                                <span class="ri-delete-bin-line"></span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {# ---- Paginator ---- #}
    {% if page_obj.has_other_pages %}
        <nav aria-label="Page navigation bootstrap">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">First page</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">&laquo;</span></a>
                    </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active" aria-current="page">
                            <span class="page-link">{{ num }}</span>
                        </li>
                    {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"><span aria-hidden="true">&raquo;</span></a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last page</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
    {# ---- Paginator ---- #}
    {# ---- JavaScript ---- #}
    {% comment %} <script type="text/javascript">
     function OpenModal(id) {
         console.log("rrereer" + id);
         modal.insertAdjacentHTML("afterbegin", `{% include "crm/obj_read.html" %}`);
         modal.showModal();
     }
 </script> {% endcomment %}
    {# ---- JavaScript ---- #}
{% endblock content %}